# Build settings
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

mathjax: true
permalink: pretty
paginate: 5

# Site identity
title: "凱達的个人主页"
tagline: "Cherub’s Little Wonderland"
description: "Eventually, all things merge into one, and a river runs through it."

# IMPORTANT: user site => baseurl should be empty
baseurl: ""

github_username: cherubwu

# Collections
collections:
  journals:
    output: true

include:
  - _pages
  - _posts
  - _journals

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

author:
  name: "Cherub Wu"
  url: "https://www.instagram.com/cherainboow"

version: "1.0"

github:
  repo: "https://github.com/cherubwu/cherubwu.github.io"
